apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: slima4/discovery-service:latest
        ports:
        - containerPort: 8070
        env:
          - name: EUREKA_INSTANCE_HOSTNAME
            value: "discovery-service"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
    selector:
        app: discovery-service
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
